version: "3.5"

services:
  hyper-threading-api-server:
    build: ./back-end/api-server/
    expose:
      - "80"
    networks:
      - hyper-threading-network
    restart: always

  hyper-threading-file-server:
    build: .
    expose:
      - "80"
    # ports:
    #   - "80:80"
    networks:
      - hyper-threading-network
    restart: always

networks:
  hyper-threading-network:
    name: rjnewsite_default
